### PR TITLE
generate zipped goto and action tables

### PR DESCRIPTION
**Pull request by awalterschulze**
As discussed in issue https://github.com/goccmack/gocc/issues/28

I used the katydid repo to benchmark this change, since it has very big tables
https://github.com/katydid/katydid

I only tested using go 1.7 I didn't try the new go 1.8 changes that are mentioned in the issue.

```
$ go version
go version go1.7 darwin/amd64
```

To reproduce clone katydid and go into the relapse/bnf folder

```
$ cd relapse/bnf/
```

Current generated code

```
$ time gocc -o .. all.bnf

real    0m24.734s
user    0m40.693s
sys 0m0.211s

$ wc -l ../parser/gototable.go
  119038 ../parser/gototable.go

$ wc -l ../parser/actiontable.go
  105239 ../parser/actiontable.go

$ time gofmt -l -s -w ../parser/
../parser/action.go
../parser/actiontable.go
../parser/gototable.go
../parser/parser.go
../parser/productionstable.go

real    0m1.539s
user    0m1.812s
sys 0m0.043s

$ time go install ../parser/

real    0m5.805s
user    0m7.608s
sys 0m0.359s
```

New generated code

```
$ time gocc -zip -o .. all.bnf

real    0m23.699s
user    0m39.755s
sys 0m0.181s

$ wc -l ../parser/gototable.go
  433 ../parser/gototable.go

$ wc -l ../parser/actiontable.go
  1092 ../parser/actiontable.go

$ time gofmt -l -s -w ../parser/
../parser/action.go
../parser/actiontable.go
../parser/gototable.go
../parser/parser.go
../parser/productionstable.go

real    0m0.094s
user    0m0.092s
sys 0m0.009s

$ time go install ../parser/

real    0m0.969s
user    0m1.335s
sys 0m0.124s
```

Code generation time is about the same.

The amount of generated code is about 100 - 200 times less.

gofmt is about a 100 times faster, but this is still small compared to the generation time.

The go install time is about 5 times faster.

### CODE REVIEW

**Comment by awalterschulze** [comment]
There is still some cleaning up to do, but I think we should first decide if this is something we want.
I think just having code base so much less influenced by having a 100 times less generated code might be worth it.
What do you @mewmew @goccmack think?

**Comment by awalterschulze** [comment]
Ok I decided I really want this.
Do you have any objections if I merge this?
@goccmack @mewmew

**Comment by mewmew** [comment]
@awalterschulze, Hej! Sorry for the delay. I finally had time to take a deeper look. Really surprised you managed to achieve this in only ~150 lines of code. Looks clean to use gzip and gob, with hex output. This is a great time saver for development, and when something looks strange, I shift back to regular output with debug enabled. I am glad this is not the default, but guarded by the `-zip` flag. Still think we may mark the `-zip` flag as experimental, but definitely add it to gocc so we can use it and further stress test it. If we decide to revisit this in the future, and evaluate against a proper implementation of Pager's "practical general method", we can evaluate both side by side.

For now, I must say, I would also very much like to start using this, as it shaves of roughly 30% of the time from tasks I run 50x times a day :) Thank you very much for pushing this forward.

Here are some results from using your zip implementation to generate the lexer and parser of the [LLVM IR library](https://github.com/llir/llvm/blob/parser/asm/internal/ll.bnf) which is currently under heavy development.

# Lines of code

## Before

```
u@x1 ~/D/g/s/g/l/l/a/internal> cloc .
      47 text files.
      47 unique files.                              
      17 files ignored.

github.com/AlDanial/cloc v 1.70  T=0.97 s (31.1 files/s, 204530.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                              17           4796           1581         190790
C                               10             31              0            142
make                             2             11              1             53
Bourne Shell                     1              0              0             26
-------------------------------------------------------------------------------
SUM:                            30           4838           1582         191011
-------------------------------------------------------------------------------
```

## After

```
u@x1 ~/D/g/s/g/l/l/a/internal> cloc .
      47 text files.
      47 unique files.                              
      17 files ignored.

github.com/AlDanial/cloc v 1.70  T=0.16 s (183.9 files/s, 165304.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                              17           3175           1581          21941
C                               10             31              0            142
make                             2             11              1             53
Bourne Shell                     1              0              0             26
-------------------------------------------------------------------------------
SUM:                            30           3217           1582          22162
-------------------------------------------------------------------------------
```

# Lexer and parser generation time

## Before

```
u@x1 ~/D/g/s/g/l/l/a/internal> time gocc ll.bnf
real 2.16
user 2.89
sys 0.02
```

## After

```
u@x1 ~/D/g/s/g/l/l/a/internal> time gocc -zip ll.bnf
real 2.02
user 2.66
sys 0.02
```

# Compilation time

## Before

```
u@x1 ~/D/g/s/g/l/l/a/internal> time go install -a ./...
real 9.62
user 15.41
sys 0.66
```

## After

```
u@x1 ~/D/g/s/g/l/l/a/internal> time go install -a ./...
real 6.00
user 12.08
sys 0.53
```

# Testing time

## Before

```
u@x1 ~/D/g/s/g/l/l/a/internal> time go test ./...
?       github.com/llir/llvm/asm/internal/errors    [no test files]
ok      github.com/llir/llvm/asm/internal/irx   0.705s
?       github.com/llir/llvm/asm/internal/lexer [no test files]
ok      github.com/llir/llvm/asm/internal/parser    0.006s
?       github.com/llir/llvm/asm/internal/token [no test files]
?       github.com/llir/llvm/asm/internal/util  [no test files]
real 5.67
user 7.94
sys 0.37
```

## After

```
u@x1 ~/D/g/s/g/l/l/a/internal> time go test ./...
?       github.com/llir/llvm/asm/internal/errors    [no test files]
ok      github.com/llir/llvm/asm/internal/irx   0.703s
?       github.com/llir/llvm/asm/internal/lexer [no test files]
ok      github.com/llir/llvm/asm/internal/parser    0.011s
?       github.com/llir/llvm/asm/internal/token [no test files]
?       github.com/llir/llvm/asm/internal/util  [no test files]
real 1.87
user 3.30
sys 0.14
```

# Summary

## Lines of code

88% less lines of code.

## Lexer and parser generation time

6% faster generation.

## Compilation time

37% faster compilation.

## Testing time

32% faster testing.

So from me, you have a +1 for sure to merge this! Great work.

**Comment by awalterschulze** [comment]
Ok awesome.

I'll see if I can clean it up and merge it asap.

**Comment by awalterschulze** [comment]
Ok I guess its clean enough :)

**Comment by awalterschulze** [comment]
Yeah just deleted 2/3s of my project or over 220 000 lines of code
https://github.com/katydid/katydid/commit/2c0e1b81d533a9cc7e350e1addaf6e1e401f4849

**Comment by mewmew** [comment]
Lovely : ) Great job!

**Pull request merged**
