### PR TITLE
Add users section in README

### PR DESCRIPTION
**Pull request by shivansh**
Add an initial entry for [gogo](https://github.com/shivansh/gogo) as suggested by @awalterschulze.

PS. The refactoring of the BNF file by moving functions for ast construction in an ast package as suggested before is under progress. It will look much cleaner then.

### CODE REVIEW

**Comment by shivansh** [comment]
Done. Apologies for the delay.

**Comment by awalterschulze** [comment]
The description looks good, but it is a bit long, if we are going to start adding more projects.  What about just:

```
[gogo](https://github.com/shivansh/gogo) - [BNF file](https://github.com/shivansh/gogo/blob/master/src/lang.bnf) - a Go to MIPS compiler written in Go
```

Or something like that?

**Comment by awalterschulze** [comment]
Sorry about being so pedantic.

**Comment by shivansh** [comment]
No worries ; longer description seemed a bit awkward to me too :sweat_smile:

**Comment by mewmew** [comment]
> I'll add mine to this list after it is merged.

Sounds good.

> Can you also add your projects @mewmew

Sure, I'll prepare a PR.

> What do you think?

LGTM, feel free to merge.

**Pull request merged**
