### PR TITLE
Move Gocc internal packages to internal directory

### LINKED ISSUE #42: API stability and exported methods
I'd like to start a discussion regarding the exported API of Gocc. Which packages should be made available to end users (if any)? Within these packages, which exported identifiers should be made available, and which are only intended to be used by gocc internally.

The main reason for raising this question is that the answer dictates how we may develop gocc in the future. If the only interface we promise to keep stable is the command line interface, than we may change the internal implementation of Gocc as need arise and restructure its internal components.

I would personally wish to do a rather extensive cleanup of the internal packages used by Gocc, and was wondering if there are any known use cases where one may want to import a package from the gocc repository directly, rather than relying on the generated `lexer` and `parser` packages?

Personally, I've never found that to be the case, that is, I've never encountered a use case where an end-user of Gocc may wish to import `github.com/goccmack/gocc/<pkgname>` directly.

Depending on the outcome if this discussion, I would suggest that all packages internal to Gocc are clearly marked as such; preferably using the [internal](https://golang.org/s/go14internal) directory package structure introduce by the Go tool chain.

This is the approach takes by two of the projects I'm involved with which relies on Gocc, namely

https://github.com/graphism/dot
https://github.com/llir/llvm

Both of these projects hide internal details of the implementation using `internal` directories. More specifically, the packages which are automatically generated by Gocc are considered internal; e.g. https://github.com/graphism/dot/tree/master/internal

* graphism/dot/internal/astx
* graphism/dot/internal/errors
* graphism/dot/internal/lexer
* graphism/dot/internal/parser
* graphism/dot/internal/token
* graphism/dot/internal/util

The `dot` package in this example then takes the approach of providing dedicated packages intended for end users, such as package [ast](https://godoc.org/github.com/graphism/dot/ast) and package [dot](https://godoc.org/github.com/graphism/dot) covering the AST of DOT files and functions for parsing DOT files, respectively.

The benefit of this approach, is that it enables Gocc to continue evolving without breaking any API promises to end-users.

My intention is to initiate this discussion, and try to figure out if there are any use-cases of the Gocc packages that I have not thought of.

I personally see Gocc as a tool, and its API promise to the users is only relevant in regards to the command line interface.

Should you all agree, I'd be happy to prepare a PR which moves internal components into an `internal` directory, before starting to prepare some more extensive cleanup PRs and refactoring efforts.

Hope to hear from you : )

CC: @goccmack, @awalterschulze

### PR DESCRIPTION
**Pull request by mewmew**
Fixes #42.

### CODE REVIEW

**Comment by awalterschulze** [comment]
LGTM.

But I have a question.
I see you haven't moved the example and test folders to internal as well?

**Comment by mewmew** [comment]
> I see you haven't moved the example and test folders to internal as well?

I wasn't sure if we wished to move these. Would it be safe to assume that no one would ever import a test case or an example? The benefit of having the examples in the root of the repo is that anyone may find them at first glance. However, we may safely move these to the `internal` directory, and simply link to the example directory from the project README. I'm up for any direction, and would be interested to hear your thoughts.

**Comment by awalterschulze** [comment]
I am new to internal so I was just wondering what the normal thing to do in
this case would be.

**Comment by mewmew** [comment]
I'm fairly new to `internal` as well, so we learn as we go. Do you have a preference in either direction? I'd be happy to move `test` and `example` into the internal directory, or leave them outside. Both works.

My reasoning for leaving them outside was that they could not be considered a part of the external API in the first place, and are thus not required to guard behind an internal directory.

**Comment by awalterschulze** [comment]
I think maybe test can move to internal and example can stay outside, because examples are like docs, but tests can live closer to the code.
But thats just a random opinion which has no ground to stand on.

**Comment by mewmew** [comment]
Sounds good to me, I'll update the PR within the days to come : )

**Comment by mewmew** [comment]
@awalterschulze Now the test cases have been moved to the `internal` directory. Feel free to merge when you've had a chance to look at it : )

Cheers /u

**Comment by awalterschulze** [comment]
On a plane. LGTM

You can merge

**Comment by mewmew** [comment]
> On a plane. LGTM You can merge

Thanks. I've merged now. Have a safe trip.

**Pull request merged**
