### PR TITLE
Cleanup: Eliminate gofmt deltas

### PR DESCRIPTION
**Pull request by kfsone**
Small change that causes make regenerate output to match what gofmt would produce.

Before:
https://gist.github.com/kfsone/08956cdb42ed13c35a433ee5be24f840

After:
(git checkout --force . && make -C example regenerate && make -C internal/test regenerate) >/dev/null && gofmt -l -s -d .

produces no output.

### CODE REVIEW

**Comment by kfsone** [comment]
In the checks, we should see no files listed as modified by gofmt or goimports.

**Comment by kfsone** [comment]
image

**Comment by awalterschulze** [comment]
Amazing.

So now it is technically unnecessary to run gofmt after running gocc?

I did this with `goderive`, another code generator as well, since gofmt can be quite slow on large files.

**Comment by kfsone** [comment]
> So now it is technically unnecessary to run gofmt after running gocc?

Yep - we could probably refactor the Makefile into an incremental sequence culminating in make ci:

- go install .
- make -C * regenerate
- make test
- golangci-lint (it runs gofmt and goimports anyway, could be configured to write the changes while its at it),
- diff check

**Comment by awalterschulze** [comment]
I was just interested and happy with the result :)

**Pull request merged**
