### PR TITLE
Fixes to makefile

### PR DESCRIPTION
**Pull request by shivansh**
- travis: Avoid calling gofmt twice in travis recipe

- errcheck: Avoid checking errors in fmt.Fprintf() statements
  Reference: https://github.com/kisielk/errcheck/issues/143

### CODE REVIEW

**Comment by shivansh** [comment]
I had one more concern - the `govet` recipe isn't being used currently in the `travis` recipe, is it advisable to invoke it during the travis build ?

**Comment by awalterschulze** [comment]
I have a feeling govet is not passing, but if it is then please include it in the travis build target.

**Comment by shivansh** [comment]
> I have a feeling govet is not passing, but if it is then please include it in the travis build target.

I tested on `go version go1.10.2 linux/amd64`, and govet passes. Adding it then.

**Comment by shivansh** [comment]
Oh, the travis build fails due to govet. Don't know how it is passing on my machine. I'll investigate this a bit.

**Comment by shivansh** [comment]
@awalterschulze PTAL at your convenience. The govet failure was a false positive.

**Pull request merged**
