### PR TITLE
added make regenerate and regenerate all examples and tests

### PR DESCRIPTION
**Pull request by awalterschulze**

### CODE REVIEW

**Comment by mewmew** [comment]
Looks good.

Would you mind adding a `goimports` invocation from the regenerate rule?

The current diff changes the import order.

```diff
 import (
 
 	// "fmt"
 	// "github.com/goccmack/gocc/example/astx/util"
 
+	"github.com/goccmack/gocc/example/astx/token"
 	"io/ioutil"
 	"unicode/utf8"
-
-	"github.com/goccmack/gocc/example/astx/token"
 )
```

**Comment by awalterschulze** [comment]
I have added goimports and also changed the templates to do this right in the first place.

**Comment by awalterschulze** [comment]
On second thought, I have removed goimports, since this introduces a new dependency and we don't currently have any dependencies in this project.

**Comment by awalterschulze** [comment]
But the generated code is now goimports compatible.

**Comment by mewmew** [comment]
> I have added goimports and also changed the templates to do this right in the first place.

Great!

> But the generated code is now goimports compatible.

Lovely.

I use goimports along with golint and other tools to validate this on every commit using Travis CI. While it does introduce a Travis dependency, it also provides a sanity check of the code. But then again, I guess the same could be argued for adding gographviz test cases as a Travis dependency.

**Comment by mewmew** [comment]
You have a :+1: from me to merge this.

**Comment by awalterschulze** [comment]
Yes I am ok with adding goimports etc as part of the travis build, but not
as part of a plain regenerate

**Comment by mewmew** [comment]
> Yes I am ok with adding goimports etc as part of the travis build, but not as part of a plain regenerate

**Comment by mewmew** [comment]
I'm curious if we should discuss the review process of Gocc. Should we require to collaborators to +1 a PR before merging it, or is one enough if not otherwise specified by CC:ing specific people?

**Comment by awalterschulze** [comment]
I prefer to at least have a plus one from one of the two of you and no objections, before I merge code I changed. 
I am also happy when you merge something, someone else is trying to contribute.
But thats my opinion.
@goccmack what do you think?

**Comment by mewmew** [comment]
Sounds good to me. Thanks for merging this! Already in use at llir/llvm : )

**Pull request merged**
