### PR TITLE
check all errors

### PR DESCRIPTION
**Pull request by awalterschulze**
This also adds errcheck to travis, to make sure we don't ever go back.

### CODE REVIEW

**Comment by awalterschulze** [comment]
fixes https://github.com/goccmack/gocc/issues/37

**Comment by awalterschulze** [comment]
I replaced `buf.WriteString(...)` with `fmt.Fprintf(buf, ...)` since errcheck thinks not checking the error return by fmt is reasonable.  Although this is a very debatable point, I don't think this really changes anything in our code and now we have proper error checking for all other functions.

**Comment by awalterschulze** [comment]
Also most importantly the generated code now passes errcheck.

**Comment by mewmew** [comment]
Hi Walter,

It's lovely that you've implemented error checking and added errcheck to travis. I agree that `fmt.Fprintf` works well for `bytes.Buffer` writers, since the likelyhood of them failing is very low and only happens if the system completely runs out of memory. When `fmt.Fprintf` is used with an `io.Writer` that may be a file though, we should definitely check the error.

I've downloaded your changes locally and they look great. All my use cases are still passing, and I'd be happy to merge this PR.

Cheers /u

**Pull request merged**
