### PR TITLE
main: remove unused functions

### PR DESCRIPTION
**Pull request by shivansh**

### CODE REVIEW

**Comment by awalterschulze** [comment]
Looks like we have a problem with go1.10 on travis, but otherwise this looks good to ship

**Comment by shivansh** [comment]
The build failure is due to errcheck failing on go1.10 (https://github.com/kisielk/errcheck/issues/167) and IMO is unrelated to the changes introduced in this PR.

**Comment by awalterschulze** [comment]
Can we remove the go1.10 check and replace it with a newer version?

**Comment by shivansh** [comment]
Yes, I think we can temporarily disable go1.10 from the travis builds until this issue is resolved in errcheck.

**Comment by awalterschulze** [comment]
Or permanently

**Comment by shivansh** [comment]
Sure. With #93 merged, I think this PR is also good to merge ?

**Comment by awalterschulze** [comment]
Agreed

**Pull request merged**
