### PR TITLE
gocc: Remove copyright notice from generated files.

### LINKED ISSUE #44: Copyright notice included in generated files
While the code of Gocc is goverened under an Apache License, the majority of the generated files do not contain a copyright notice. This is a good thing, as it allows parser developers to license their parsers in whichever way they wish.

However, the copyright notice is included in two of the generated files, namely:
* internal/util/gen/golang/litconv.go
* internal/util/gen/golang/rune.go

For reference, no copyright notice is included in any of the files generated from:
* internal/lexer/gen/golang/acttab.go
* internal/lexer/gen/golang/asciitable.go
* internal/lexer/gen/golang/lexer.go
* internal/lexer/gen/golang/transtab.go
* internal/parser/gen/golang/action.go
* internal/parser/gen/golang/actiontable.go
* internal/parser/gen/golang/actiontable.go
* internal/parser/gen/golang/errors.go
* internal/parser/gen/golang/gototable.go
* internal/parser/gen/golang/gototable.go
* internal/parser/gen/golang/parser.go
* internal/parser/gen/golang/productionstable.go
* internal/token/gen/golang/token.go

### PR DESCRIPTION
**Pull request by mewmew**
Fixes #44.

### CODE REVIEW

**Comment by awalterschulze** [comment]
I think you just need to regenerate, but then I approve.

**Comment by mewmew** [comment]
> I think you just need to regenerate, but then I approve.

Regenerated.

**Comment by mewmew** [comment]
And thanks Walter! I'm impressed by your response time :)

**Comment by mewmew** [comment]
I love that you have added a Travis check to diff the output using "make regenerate". Forgot you had implemented that CI feature a while back. Very glad to see it in action!

**Comment by awalterschulze** [comment]
Well response time is because I am at home trying to do some haskell parsec :)
I approve.  You can merge this.
I love automated builds approvals for pull requests.

**Comment by mewmew** [comment]
> haskell parsec

Oh, lovely!!

Haha, now I feel jealous. I do belive the Haskell type system was meant for writing ASTs and the like, while in Go, you have to jump through hoops to make it behave.

**Comment by awalterschulze** [comment]
Yes well with Parsec you have to constantly think about LL(1) or other lookahead.  Its not ideal, but pretty cool for building the ast.
I still prefer gocc, but gocc could be faster if the go type system was less naive and gocc didn't have to do type assertions the whole time.

**Pull request merged**
