### PR TITLE
all: ensure that Gocc generated code conforms to gofmt

### LINKED ISSUE #36: Ensure that Gocc generated code conforms to gofmt
Ref: https://travis-ci.org/llir/llvm/builds/180995728
```
### gofmt
./asm/internal/token/token.go
./asm/internal/lexer/lexer.go
./asm/internal/lexer/transitiontable.go
./asm/internal/lexer/acttab.go
./asm/internal/parser/actiontable.go
./asm/internal/parser/productionstable.go
./asm/internal/parser/gototable.go
./asm/internal/parser/action.go
./asm/internal/parser/parser.go
./asm/internal/util/rune.go
./asm/internal/util/litconv.go
./asm/internal/errors/errors.go
```

Extract from `gofmt -d`

```diff
diff ./util/litconv.go gofmt/./util/litconv.go
--- /tmp/gofmt318333961	2016-12-04 12:01:27.498715220 +0100
+++ /tmp/gofmt274563540	2016-12-04 12:01:27.498715220 +0100
@@ -1,4 +1,3 @@
-
 // generated by gocc; DO NOT EDIT.
 
 //Copyright 2013 Vastech SA (PTY) LTD
diff ./util/rune.go gofmt/./util/rune.go
--- /tmp/gofmt147755799	2016-12-04 12:01:27.502048553 +0100
+++ /tmp/gofmt271031690	2016-12-04 12:01:27.502048553 +0100
@@ -1,4 +1,3 @@
-
 // generated by gocc; DO NOT EDIT.
 
 //Copyright 2013 Vastech SA (PTY) LTD
diff ./parser/parser.go gofmt/./parser/parser.go
--- /tmp/gofmt528173389	2016-12-04 12:01:27.522048553 +0100
+++ /tmp/gofmt702109256	2016-12-04 12:01:27.522048553 +0100
@@ -1,9 +1,8 @@
-
 // generated by gocc; DO NOT EDIT.
 
 package parser
 
-import(
+import (
 	"bytes"
 	"fmt"
 
@@ -20,16 +19,16 @@
 // Stack
 
 type stack struct {
-	state []int
-	attrib	[]Attrib
+	state  []int
+	attrib []Attrib
 }
 
 const iNITIAL_STACK_SIZE = 100
 
 func newStack() *stack {
-	return &stack{ 	state: 	make([]int, 0, iNITIAL_STACK_SIZE),
-					attrib: make([]Attrib, 0, iNITIAL_STACK_SIZE),
-			}
+	return &stack{state: make([]int, 0, iNITIAL_STACK_SIZE),
+		attrib: make([]Attrib, 0, iNITIAL_STACK_SIZE),
+	}
 }
 
 func (this *stack) reset() {
@@ -42,8 +41,8 @@
 	this.attrib = append(this.attrib, a)
 }
 
-func(this *stack) top() int {
-	return this.state[len(this.state) - 1]
+func (this *stack) top() int {
+	return this.state[len(this.state)-1]
 }
 ...
```

### PR DESCRIPTION
**Pull request by mewmew**
Fixes #36.

### CODE REVIEW

**Comment by mewmew** [comment]
@awalterschulze Wait for just a moment before merging. Currently fixing the output of files generated without the `-zip` flag.

**Comment by mewmew** [comment]
@awalterschulze Feel free to review whenever you wish. I've submitted the last changes so that the generated files (both with and without `-zip`) conform to gofmt. Note, three of these files had huge tables where indentation of fields had to be adjusted dynamically based on the length of individual field members. For these cases, [format.Source](https://golang.org/pkg/go/format/#Source) was used and the output has been verified to conform to running `gofmt`.

**Comment by awalterschulze** [comment]
We should probably then remove the gofmt from the regenerate target in the Makefile
https://github.com/goccmack/gocc/blob/master/Makefile#L19

**Comment by awalterschulze** [comment]
Ok I see format source on three places.  Was it really not possible not to use format source. 
Maybe you can just post an example of something that is hard to code generate correctly.  I am sure there is, but I would just like to see it for myself, if thats ok?  Basically just a snippet of something that was one of the reasons that you needed to add format.Source.

**Comment by mewmew** [comment]
> We should probably then remove the gofmt from the regenerate target in the Makefile
https://github.com/goccmack/gocc/blob/master/Makefile#L19

Similar to errcheck I think it is good to have a gofmtcheck to ensure that the code is actually conforming (and continues to conform) to the gofmt format.

**Comment by awalterschulze** [comment]
I think thats what the travis target is for.
If we guarantee gofmt, we should also trust it in our own dev.
travis is there to catch our mistakes.

By not requiring the user to gofmt their generated code, we speed up their development cycle.
When the files you edit are being gofmted by your editor and all your generated code is already gofmted, their is no reason to rerun gofmt over all your code.  gofmt can become quite slow on a large project.  So this would be a great win and we should go for it 100%

**Comment by awalterschulze** [comment]
With my goderive code generator, I am even testing that regenerated code is gofmted.
https://github.com/awalterschulze/goderive/blob/master/test/normal/Makefile#L5-L12

**Comment by mewmew** [comment]
Using [llirllvm/asm/internal/ll.bnf](https://github.com/llir/llvm/blob/master/asm/internal/ll.bnf) as a basis for this example.

The three files which requires gofmt for correct alignment are

* ./parser/actiontable.go
* ./parser/gototable.go
* ./token/token.go

Giving an example from actiontable.go

```diff
 var actionTab = actionTable{
 	actionRow{ // S0
 		canRecover: false,
 		actions: [numSymbols]action{
-			nil,		/* INVALID */
-			reduce(2),		/* $, reduce: TopLevelDecls */
-			nil,		/* empty */
-			shift(17),		/* source_filename */
-			nil,		/* = */
-			nil,		/* string_lit */
-			shift(18),		/* target */
-			nil,		/* datalayout */
-			nil,		/* triple */
-			shift(19),		/* module */
-			nil,		/* asm */
-			nil,		/* type */
-			nil,		/* opaque */
-			nil,		/* comdat */
-			nil,		/* any */
-			nil,		/* exactmatch */
-			nil,		/* largest */
-			nil,		/* noduplicates */
-			nil,		/* samesize */
-			nil,		/* , */
-			nil,		/* externally_initialized */
-			nil,		/* constant */
-			nil,		/* global */
-			shift(23),		/* declare */
-			shift(24),		/* define */
-			nil,		/* ( */
-			nil,		/* ) */
-			nil,		/* ... */
-			nil,		/* { */
-			nil,		/* } */
-			shift(25),		/* attributes */
-			nil,		/* ! */
-			nil,		/* distinct */
-			shift(28),		/* global_ident */
-			shift(29),		/* local_ident */
-			nil,		/* label_ident */
-			nil,		/* attr_group_id */
-			shift(30),		/* comdat_name */
-			shift(31),		/* metadata_name */
-			shift(32),		/* metadata_id */
-			nil,		/* void */
-			nil,		/* int_type */
-			nil,		/* half */
-			nil,		/* float */
-			nil,		/* double */

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
+			nil,       /* INVALID */
+			reduce(2), /* $, reduce: TopLevelDecls */
+			nil,       /* empty */
+			shift(17), /* source_filename */
+			nil,       /* = */
+			nil,       /* string_lit */
+			shift(18), /* target */
+			nil,       /* datalayout */
+			nil,       /* triple */
+			shift(19), /* module */
+			nil,       /* asm */
+			nil,       /* type */
+			nil,       /* opaque */
+			nil,       /* comdat */
+			nil,       /* any */
+			nil,       /* exactmatch */
+			nil,       /* largest */
+			nil,       /* noduplicates */
+			nil,       /* samesize */
+			nil,       /* , */
+			nil,       /* externally_initialized */
+			nil,       /* constant */
+			nil,       /* global */
+			shift(23), /* declare */
+			shift(24), /* define */
+			nil,       /* ( */
+			nil,       /* ) */
+			nil,       /* ... */
+			nil,       /* { */
+			nil,       /* } */
+			shift(25), /* attributes */
+			nil,       /* ! */
+			nil,       /* distinct */
+			shift(28), /* global_ident */
+			shift(29), /* local_ident */
+			nil,       /* label_ident */
+			nil,       /* attr_group_id */
+			shift(30), /* comdat_name */
+			shift(31), /* metadata_name */
+			shift(32), /* metadata_id */
+			nil,       /* void */
+			nil,       /* int_type */
+			nil,       /* half */
+			nil,       /* float */
+			nil,       /* double */
```

**Comment by awalterschulze** [comment]
Hmmm.  Technically we know whether its a shift, reduce or nil when we generate.  So we could adjust the spaces.  And this is quite a large large to go over again and reformat.
The template code will look horrible, if we add these ifs.
So I guess its a trade off.
What is your feeling on this?

**Comment by mewmew** [comment]
> Hmmm. Technically we know whether its a shift, reduce or nil when we generate. So we could adjust the spaces. And this is quite a large large to go over again and reformat.
The template code will look horrible, if we add these ifs.
So I guess its a trade off.

Even with knowledge of whether it is a shift or reduce, we would also have to check the length of the digit, i.e. 0-9 is 1 byte, 10-99 is 2 bytes, etc. since that also affects space alignment.

> What is your feeling on this?

In general my feeling is to, use the right tool for the job when possible. So, when the format is rather static, we output correctly formatted code our selves. When the format is of dynamic nature, we use a formatting tool instead of reimplementing that logic.

That being said, we may need to be pragmatic about this as the generated files may be *huge* sometimes. Did a quick check to see how long time `gofmt` takes for `./parser/gototable.go`

```
u@x220 ~/D/g/s/g/l/l/a/internal> time gofmt -w ./parser/gototable.go
real 35.80
user 38.71
sys 1.13
```

The formatting needed for `` is as follows:

```diff
 var gotoTab = gotoTable{
 	gotoRow{ // S0
-		-1, // S'
-		1, // Module
-		2, // TopLevelDecls
-		3, // TopLevelDeclList
-		4, // TopLevelDecl
-		5, // SourceFilename
-		6, // TargetSpec
-		-1, // DataLayout
-		-1, // TargetTriple
-		7, // ModuleAsm
-		8, // TypeDef
-		9, // ComdatDef
-		-1, // SelectionKind
-		10, // GlobalDecl
-		11, // GlobalDef
-		-1, // GlobalOptions
+		-1, // S'
+		1,  // Module
+		2,  // TopLevelDecls
+		3,  // TopLevelDeclList
+		4,  // TopLevelDecl
+		5,  // SourceFilename
+		6,  // TargetSpec
+		-1, // DataLayout
+		-1, // TargetTriple
+		7,  // ModuleAsm
+		8,  // TypeDef
+		9,  // ComdatDef
+		-1, // SelectionKind
+		10, // GlobalDecl
+		11, // GlobalDef
+		-1, // GlobalOptions
```

The `parser/gototable.go` file is 2.8 million lines of code for `llir/llvm`, so it is understandable that gofmt takes around 35 seconds.

Still, since there are three rather huge files that would need dynamic formatting, the added runtime for large projects may be above a minute or two, which I think is not reasonable.

So, I think you are right. We may need to calculate this ourselves and add support for dynamic alignment of spaces, even if the template code for these three files may end up looking horrible.

What's your view on this?

**Comment by mewmew** [comment]
Perhaps we could hook this up using [text/tabwriter](https://golang.org/pkg/text/tabwriter/) somehow.

**Comment by awalterschulze** [comment]
Ah I didn't think about the length of the numbers.  That is a really good point and would have sold me on using format.Source.

But then you mentioned 2.8 million lines.  Are you sure?  Holy shit thats a lot.
Are you sure you don't want to use `-zip`?

**Comment by mewmew** [comment]
> Are you sure you don't want to use -zip?

I am using zip and love it! Only switched back to not using -zip for this pull request, so that both outputs will be correctly gofmt'ed

**Comment by mewmew** [comment]
> But then you mentioned 2.8 million lines. Are you sure? Holy shit thats a lot.

Indeed. Makes me wish we had https://github.com/goccmack/gocc/issues/34 or LALR :)

**Comment by awalterschulze** [comment]
Yes wow.  I think you should post your use case on the issue.  At least then it pushes up the priority somewhat.

**Comment by mewmew** [comment]
Oh, and another reason for switching back to not using `-zip`, is that's impossible to track code coverage of production rules using `-zip`. In my mind, that's its primary drawback.

**Comment by awalterschulze** [comment]
Aha thats also interesting.

**Comment by mewmew** [comment]
With `-zip`, there is always 100% code coverage of production rules.

**Comment by awalterschulze** [comment]
Didn't even think about using code coverage for a generated parser, but I think that might be the one case where it makes a lot of sense.

**Comment by mewmew** [comment]
Indeed. Having gone through the various production rules of the LLVM IR grammar, we ended up finding so many little mistakes that look correct in the grammar, but end up being wrong. Even the empty grammar had an incorrect assumption :p So, at least for me, working on this kind of code I tend to rely on heavy use of test cases.

**Comment by awalterschulze** [comment]
So in conclusion:
 - I'll sacrifice some code readability for code generation speed.
 - I am ok with format.Source, but would prefer something faster.
   - If tabwriter is that faster thing, then great.
    - If it is some other method, then I am also happy.
 - I think the code generation speed is just as important as go compile speed and non go formatted code is not finished generating yet.

**Comment by awalterschulze** [comment]
Yes tests for parsers (and everything) are essential, but I rarely use code coverage.

**Comment by mewmew** [comment]
> So in conclusion:
> 
>     I'll sacrifice some code readability for code generation speed.
>     I am ok with format.Source, but would prefer something faster.
>         If tabwriter is that faster thing, then great.
>         If it is some other method, then I am also happy.
>     I think the code generation speed is just as important as go compile speed and non go formatted code is not finished generating yet.

I think you summarized my thoughts as well.

Having looked at tabwriter, I think it may be overkill, also as it needs to keep everything in memory until its done. Simply calculating the padding based on the max length of a field may be enough. I'll try this route first.

**Comment by mewmew** [comment]
> Yes tests for parsers (and everything) are essential, but I rarely use code coverage.

You are missing out on all the pretty colours :) Here's one example from graphism/dot:

https://coveralls.io/builds/9789872/source?filename=internal%2Fparser%2Fproductionstable.go

**Comment by awalterschulze** [comment]
Ok yes, those are some pretty colors :)

**Comment by mewmew** [comment]
> Yes wow. I think you should post your use case on the issue. At least then it pushes up the priority somewhat.

Added an update to https://github.com/goccmack/gocc/issues/34#issuecomment-309427011

**Comment by mewmew** [comment]
Right.

So, I've stumbled upon a bit of an annoyance.

The following is properly gofmt'ed code:

```go
package p

var x = map[string]int{
	"a":                  1,
	"b":                  1,
	"cccccccccccccccccc": 2,
	"dddd":               2,
}
```

and so is

```go
package p

var x = map[string]int{
	"a": 1,
	"b": 1,
	"ccccccccccccccccccc": 2,
	"dddd":                2,
}
```

It seems like there is a break-of point for how much padding gofmt will do.

This is commonly occurring in `token/token.go` for the `idMap: map[string]Type` literal.

I've managed to fix tables used by the parser (i.e. actiontable.go and gototable.go) using custom padding and that works just fine.

However, for token/token.go, it is not trivial to calculate the padding ourselves.

I would rely on gofmt for these, mainly because we don't wish to reimplement too much formatting logic (especially not non-trivial one) and also because the token tables are not too large in general.

For comparison:

parser tables of `llir/llvm`:

```
u@x220 ~/D/g/s/g/l/l/a/i/parser> wc -l actiontable.go gototable.go 
  3108914 actiontable.go
  2860201 gototable.go
  5969115 total
```

token table of `llir/llvm`:

```
u@x220 ~/D/g/s/g/l/l/a/i/token> wc -l token.go 
656 token.go
```

I would vote for using `format.Source` for formatting `token/token.go` and use custom formatting and padding for the larger tables of `parser/...`.

@awalterschulze What are your thoughts?

**Comment by awalterschulze** [comment]
I agree :)

**Comment by mewmew** [comment]
Uploaded with 5aaf8a8. Should be done for merge I think.

**Comment by awalterschulze** [comment]
LGTM 
What magic is this `%*c`?

**Comment by awalterschulze** [comment]
You can merge when you are ready.

**Comment by mewmew** [comment]
> What magic is this %*c?

Padding n bytes, where n is specified using the `*` flag.

From [fmt](https://golang.org/pkg/fmt/) godoc:

> Width and precision are measured in units of Unicode code points, that is, runes. (This differs from C's printf where the units are always measured in bytes.) Either or both of the flags may be replaced with the character '*', causing their values to be obtained from the next operand, which must be of type int.
>
> For most values, width is the minimum number of runes to output, padding the formatted form with spaces if necessary. 

https://play.golang.org/p/eMB_xq-aMH

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Printf("hello%*cworld", 3, ' ')
}
```

Outputs `hello   world` with 3 spaces between `hello` and `world`.

**Comment by mewmew** [comment]
Merging.

**Comment by awalterschulze** [comment]
Wow I have been looking for that, for quite a while now.  Thanks.

**Comment by awalterschulze** [comment]
Although it doesn't seem to work very well with tabs
https://play.golang.org/p/ZeOf78pH-x

**Comment by mewmew** [comment]
> Although it doesn't seem to work very well with tabs

The padding is always spaces, and `%c` inserts the character you pass as an argument to `Printf`, so it does actually do what documented.

The output from https://play.golang.org/p/ZeOf78pH-x contains 0 spaces on the first line, 0 spaces on the second line (since that already has a character), 1 space on the third line (since that already has one character, but wants padding 2) and 2 spaces on the last line (since that already has two characters, but wants padding 3).

```
	world
	world
 	world
  	world
```

It is true that this may not be what you want, seeing as Printf is unaware of *tab width* settings. For those purposes, I think tabwriter is the right tool for the job.

Out of curiosity, when may you wish to indent with both spaces and tabs? In my experience, tabs are used for indentation and spaces are used for alignment. That is, tabs may only appear at the beginning of a line, never in the middle (i.e. after a non-tab character). For alignment in the middle of lines, use spaces, as then the alignment will be correct, no matter the setting of tab width.

**Comment by awalterschulze** [comment]
I was thinking of using it here
https://github.com/awalterschulze/goderive/blob/master/derive/printer.go#L84-L94
I would like to avoid the `+=` as I think it might be a bit slow.
But I am just guessing and `In` and `Out` are probably not a bottleneck.

Also I am assuming gofmt uses tabs at the start of the lines, which might be incorrect?

**Comment by mewmew** [comment]
> I was thinking of using it here
> https://github.com/awalterschulze/goderive/blob/master/derive/printer.go#L84-L94
> I would like to avoid the += as I think it might be a bit slow.
> But I am just guessing and In and Out are probably not a bottleneck.

Before updating to optimize code (which may decrease readability), make sure to profile so that you fix the right bottleneck.

> Also I am assuming gofmt uses tabs at the start of the lines, which might be incorrect?

It does.

**Comment by awalterschulze** [comment]
True.  For now I am rather working on adding functionality.  deep CopyTo is starting to work, even for private fields of structs in other packages.

**Pull request merged**
