### PR TITLE
gen: fix imports in source template

### PR DESCRIPTION
**Pull request by kortschak**
See https://github.com/goccmack/gocc/pull/83#issuecomment-470014589.

Please take a look. Apologies for not noticing this earlier.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Can we also fix travis to catch this in future

**Comment by kortschak** [comment]
I found it by running our gonum dot parser tests after applying the new code gen. Are there complete runnable code gen examples in the repo that can be leveraged for testing?

**Comment by kortschak** [comment]
Actually, they don't need to be runnable, just buildable.

**Comment by kortschak** [comment]
I have looked through the examples and none of those are affected by the breakage that this fixes. Finding the breakage appears to depend on including parse stack and error reporting. I'm not entirely clear how this in included.

/cc @mewmew

**Comment by mewmew** [comment]
> I'm not entirely clear how this in included.
>
> /cc @mewmew

I am not too familiar with those parts of the Gocc code. Perhaps @sangisos remembers? Alex, if I remember correctly, you looked at error reporting last time we played with this?

**Comment by awalterschulze** [comment]
Maybe I am missing something, but currently we run

```
make install
make regenerate
make govet
make goimports
make errcheck
make test
git diff --exit-code .
```

as part of `make travis`
Is is possible to add something as simple as `go build ./...` to catch this error?

**Comment by kortschak** [comment]
The issue is that the current examples do not incorporate the parser error code from those template. The Gonum dot parser does. This means that running that check does not fail here while it does in the Gonum generated code.

A possibility is to include the Gonum code which is CC0 and written by @mewmew, then run the test above.

**Comment by awalterschulze** [comment]
Or to include a very small example, that uses the error code.

**Comment by awalterschulze** [comment]
For now, I think we can merge this.

**Pull request merged**
