### PR TITLE
Add original project overview to readme, update links, fix typos, ...

### PR DESCRIPTION
**Pull request by mewmew**
* Simplify user-defined code in examples.
* Make printing of command line usage consistent in gocc.
* Update gographviz link in gocc user guide.
* Fix shift-reduce and reduce-reduce example paths in gocc user guide.

### CODE REVIEW

**Comment by goccmack** [comment]
Thanks Robin, for making gocc useable on github.

**Comment by awalterschulze** [comment]
Now you just need to change the title that still says
"Automatically exported from code.google.com/p/gocc"
And maybe delete the wiki branch.

**Comment by mewmew** [comment]
> Thanks Robin, for making gocc useable on github.

You are welcome Marius! Thank you so much for publishing Gocc in the first place. It has been an invaluable resource for me to further my understanding of compiler theory, and has been a lot of fun to play around with. My next hobby project is to try and produce an BNF for the [LLVM IR assembly language](http://llvm.org/docs/LangRef.html).

And Walter, thank you for developing the gographviz package! It was a fundamental part of my [dissertation project](https://github.com/decomp/decompilation), to implement a decompiler from LLVM IR to Go.

Cheers
- Robin

**Comment by awalterschulze** [comment]
You are working on some really cool projects, thank you for using mine :)

**Pull request merged**
