### PR TITLE
improvement: make generated code safer

### PR DESCRIPTION
**Pull request by onokonem**
how to reproduce a _closing multiline comment sequence_ problem

```
mkdir mlcomment-test
cd mlcomment-test
go mod init github.com/goccmack/gocc/mlcomment-test
echo 'MLComment: "/*" "test" "*/";' > mlcomment-test.ebnf
gocc -a -v -p github.com/goccmack/gocc/mlcomment-test mlcomment-test.ebnf
go build ./parser
```

### CODE REVIEW

**Comment by shivansh** [comment]
Thanks for the PR.
Could you also please include a small description explaining why separate handling of `*/` symbol is required ?

**Comment by onokonem** [comment]
I've updated the PR description and added a brief comment to the source

**Comment by shivansh** [comment]
Sorry for the delay on this.

For others' convenience, [this](https://gist.github.com/shivansh/1567af5d80d91a326aec521264512359/c8fee8a19d59870e958e9053d1e0936413ae55d6#file-actiontable-go-L21) is the generated (buggy) actiontable from the EBNF mentioned above, and [this](https://gist.github.com/shivansh/1567af5d80d91a326aec521264512359#file-actiontable-go-L21) is the result after applying the fix.

As an aside, Go's [spec](https://golang.org/ref/spec#Comments) uses the term _general comments_ instead of _multiline comments_ so maybe we could switch to using it.

I would personally suggest `safeSym` to be something along the lines of the following, although deferring to @awalterschulze @mewmew  for suggestions -
```
func safeSym(sym string) string {
	if sym == `*/` {
		// A '*/' token in the EBNF causes compilation error in the
		// generated actiontable due to buggy comments like `/* */ */`.
		// Avoid this by replacing them in the generated code with -
		// `/* closing general comment token */`.
		return "closing general comment token"
	} else {
		return sym
	}
}
```

**Comment by shivansh** [comment]
[Alternatively](https://github.com/shivansh/gocc/commit/4856c657fa02d4006a5c1349ad7ee4dfed5cf863), we can also replace the general comments with line comments in actiontable. [This](https://gist.github.com/shivansh/1567af5d80d91a326aec521264512359#file-actiontable-go-L21) will be the resulting actiontable.

**Comment by awalterschulze** [comment]
I like the line comments.

**Comment by shivansh** [comment]
Fixed in 07ce4bc.

**Pull request closed without merging**
