### PR TITLE
Fix bug that led to incorrect line numbers (fixes #14)

### LINKED ISSUE #14: Accessing source code line number from parsed AST nodes
Hi,

Thank you for publishing this tool. I am using it for a university assignment.
This is not an issue, but more of question/request.

I want to access source code information (line number, etc) from the AST nodes somehow. I want to display informative error messages when my later semantic analysis fails.

Is it possible to do this? Thanks in advance.

### PR DESCRIPTION
**Pull request by edwardmp**

### CODE REVIEW

**Comment by awalterschulze** [comment]
I tested this on https://github.com/katydid/katydid
It seems to break.
You can test this by installing your branch of gocc and simply running make in katydid.
It might be easier to simply regenerate and then run the tests in github.com/katydid/katydid/relapse/parser

**Comment by sangisos** [comment]
It seems like every time a token is accepted, the Scan starts over on the same position (backing up and reading again). This causes every rune after an accepted token to be counted twice.
```
	S0, : tok=INVALID (), rune == ')'(29), next state == 8
		pos=18, size=1, start=17, end=0
		action:Accept=29, Ignore=
	 Accept(Accept=29, Ignore=), )(&{29 [] {0 0 0}})
	pos=18, line=1, col=23, state=8
	S8, : tok=) (), rune == ' '(20), next state == -1
		pos=19, size=1, start=17, end=18
Lexer.Scan() pos=18
	pos=18, line=1, col=24, state=0
	S0, : tok=INVALID (), rune == ' '(20), next state == 1
		pos=19, size=1, start=18, end=0
		action:Accept=-1, Ignore=!whitespace
	 Ignore(Accept=-1, Ignore=!whitespace)
	pos=19, line=1, col=25, state=0
	S0, : tok=INVALID (), rune == '{'(7b), next state == 46
		pos=20, size=1, start=19, end=0
		action:Accept=48, Ignore=
	 Accept(Accept=48, Ignore=), {(&{48 [] {0 0 0}})
	pos=20, line=1, col=26, state=46
	S46, : tok={ (), rune == '\n'(a), next state == -1
		pos=21, size=1, start=19, end=20
Lexer.Scan() pos=20
	pos=20, line=2, col=1, state=0
	S0, : tok=INVALID (), rune == '\n'(a), next state == 1
		pos=21, size=1, start=20, end=0
		action:Accept=-1, Ignore=!whitespace
	 Ignore(Accept=-1, Ignore=!whitespace)
	pos=21, line=3, col=1, state=0
	S0, : tok=INVALID (), rune == '\t'(9), next state == 1
		pos=22, size=1, start=21, end=0
		action:Accept=-1, Ignore=!whitespace
	 Ignore(Accept=-1, Ignore=!whitespace)
```

**Comment by mewmew** [comment]
Fixed as of #30. Should we close this PR?

**Comment by mewmew** [comment]
Closing this PR has #30 included a fixed.

**Pull request closed without merging**
