### PR TITLE
implemented fix for windows-based package path generation

### LINKED ISSUE #15: Generated code has multiple Unknown Escape Sequence's
Hello!

The generated code contains faulty import paths when importing other generated code. This happens in the error, lexer and parser packages.

    // parser/parser.go
    import(
        "bytes"
        "errors"
        "fmt"
        parseError "\comp\somedir/errors"
        "\comp\somedir/token"
    )

The errors are caused by the backslashes in the import path.

### PR DESCRIPTION
**Pull request by boljen**
I haven't tested this on other platforms but windows. It should fix #15.

### CODE REVIEW

**Comment by mewmew** [comment]
Consider using [filepath.ToSlash](https://golang.org/pkg/path/filepath/#ToSlash) which is designed for this very purpose.

**Comment by boljen** [comment]
I amended the commit to use that function.

Nice catch by the way, I checked the source and it's identical to what I wrote.

**Comment by mewmew** [comment]
> I amended the commit to use that function.
>
> Nice catch by the way, I checked the source and it's identical to what I wrote.

Looks good. Lets wait for @goccmack and @awalterschulze to take a look, they are the ones with commit access as far as I know.

**Comment by awalterschulze** [comment]
LGTM :)
Are you ok with giving over your copyright for this pull request?

**Comment by boljen** [comment]
Of co urse

**Comment by awalterschulze** [comment]
Thank you :)

**Pull request merged**
